// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7V_dUn7aKZ3U58U8-INzmALbKpEi2QWY',
    appId: '1:735518718739:web:86f9164bbafcbe9e3738e6',
    messagingSenderId: '735518718739',
    projectId: 'cerca-7f98c',
    authDomain: 'cerca-7f98c.firebaseapp.com',
    storageBucket: 'cerca-7f98c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAvTRbRYzSW5VqCR_5vaDHZ8OqDuBWJTw',
    appId: '1:735518718739:android:f9f174817e1feaa43738e6',
    messagingSenderId: '735518718739',
    projectId: 'cerca-7f98c',
    storageBucket: 'cerca-7f98c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1VsX9YJWskwLMxsE_x939hygtZrY5wn4',
    appId: '1:735518718739:ios:55a5bfdb5039e92c3738e6',
    messagingSenderId: '735518718739',
    projectId: 'cerca-7f98c',
    storageBucket: 'cerca-7f98c.firebasestorage.app',
    iosClientId: '735518718739-mih6200apd0khgdccfrlkbqg2a4e78t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1VsX9YJWskwLMxsE_x939hygtZrY5wn4',
    appId: '1:735518718739:ios:55a5bfdb5039e92c3738e6',
    messagingSenderId: '735518718739',
    projectId: 'cerca-7f98c',
    storageBucket: 'cerca-7f98c.firebasestorage.app',
    iosClientId: '735518718739-mih6200apd0khgdccfrlkbqg2a4e78t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7V_dUn7aKZ3U58U8-INzmALbKpEi2QWY',
    appId: '1:735518718739:web:7f783f02bbcf135c3738e6',
    messagingSenderId: '735518718739',
    projectId: 'cerca-7f98c',
    authDomain: 'cerca-7f98c.firebaseapp.com',
    storageBucket: 'cerca-7f98c.firebasestorage.app',
  );
}
